
/*
 * ERD 클라우드 이용해서 테이블 3개 만들고
 * 디비버에서 3행씩 INSERT한 다음에 SELECT해서 우리반 게시판 과제탭에 올리기
 * 
 */

DROP TABLE "SUPPLEMENTS";

CREATE SEQUENCE SEQ_SUP_ID START WITH 4 NOCACHE;
CREATE SEQUENCE SEQ_MEM_ID START WITH 4 NOCACHE;

CREATE TABLE "SUPPLEMENTS" (
	"SUP_NO"	NUMBER		NOT NULL,
	"SUP_NAME"	VARCHAR2(50)		NOT NULL,
	"SUP_PRICE"	NUMBER		NOT NULL,
	"PILLS"	NUMBER		NOT NULL
);

DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"MEM_NO"	NUMBER		NOT NULL,
	"MEM_NAME"	VARCHAR2(50)		NOT NULL,
	"MEM_ID"	VARCHAR2(40)		NOT NULL,
	"MEM_PWD"	VARCHAR2(60)		NOT NULL,
	"MEM_ADDRESS"	VARCHAR2(1000)		NOT NULL,
	"ACCOUNT_NUM"	NUMBER		NOT NULL,
	"BANK_NAME"	VARCHAR2(20)		NOT NULL
);

DROP TABLE "SAVE";

CREATE TABLE "SAVE" (
	"MEM_NO"	NUMBER		NOT NULL,
	"SUP_NO"	NUMBER		NOT NULL,
	"SAVE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

ALTER TABLE "SUPPLEMENTS" ADD CONSTRAINT "PK_SUPPLEMENTS" PRIMARY KEY (
	"SUP_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEM_NO"
);

ALTER TABLE "SAVE" ADD CONSTRAINT "PK_SAVE" PRIMARY KEY (
	"MEM_NO",
	"SUP_NO"
);

ALTER TABLE "SAVE" ADD CONSTRAINT "FK_MEMBER_TO_SAVE_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "MEMBER" (
	"MEM_NO"
);

ALTER TABLE "SAVE" ADD CONSTRAINT "FK_SUPPLEMENTS_TO_SAVE_1" FOREIGN KEY (
	"SUP_NO"
)
REFERENCES "SUPPLEMENTS" (
	"SUP_NO"
);


INSERT INTO SUPPLEMENTS
VALUES(1,'고려은단 비타민C 1000', 17900,180);


INSERT INTO SUPPLEMENTS
VALUES(2,'고려은단 비타민C 골드 플러스', 45000,240);


INSERT INTO SUPPLEMENTS
VALUES(3,'메가도스 비타민C 3000mg', 27000,100);


INSERT INTO MEMBER
VALUES(1, '홍길동', 'USER01', 'PWD01', 'ADDRESS01', 123456789012, '하나');


INSERT INTO MEMBER
VALUES(2, '고길동', 'USER02', 'PWD02', 'ADDRESS02', 157838491913, '국민');


INSERT INTO MEMBER
VALUES(3, '둘리', 'USER03', 'PWD03', 'ADDRESS03', 472859274912, '신한');

INSERT INTO SAVE (MEM_NO,SUP_NO)
VALUES(1,1);

INSERT INTO SAVE (MEM_NO,SUP_NO)
VALUES(1,2);

INSERT INTO SAVE (MEM_NO,SUP_NO)
VALUES(2,3);

SELECT * FROM SAVE;
SELECT * FROM MEMBER;
SELECT * FROM SUPPLEMENTS;
































