SELECT 
    a.table_name AS "외래키를_쓰는_테이블(자식)", 
    a.constraint_name AS "찾아낸_외래키_이름" -- 외래키 이름은 여기서 확인하세요!
FROM 
    user_constraints a
JOIN 
    user_constraints b ON a.r_constraint_name = b.constraint_name
WHERE 
    b.constraint_type IN ('P', 'U') 
    AND b.table_name = 'MEMBER'; -- 대문자로 입력해주세요!
    
SELECT * FROM SAVE;

DROP TABLE SAVE;

SELECT * FROM MEMBER;
SELECT * FROM BOARD;

-- 나중에 만들 때는 테이블 관계를 좀 더 잘 생각해보자
-- 관계를 잘 생각하면 좋을듯, 1:1, N:M, 1:N
-- 나무 생각하면 좀 편한듯 
-- 부모의 PK를 참조해서 자식이 외래키로 사용
--(일반 컬럼에 외래키 넣으면 1:N, 
--PK컬럼에 외래키 넣으면 1:1-> 근데 PK컬럼 말고 따로 유니크 제약 조건 넣어서 외래키로 넣으면 유지보수에 좋음 같은 걸 굳이 왜 2개나 넣나 했는데 
--PK는 수정이 굉장히 어려워서 나중에 1:1에서 1:N으로 바꾸고 싶으면 쉽지 않아짐
--두 부모의 PK를 자식테이블의 두 컬럼에 외래키로 넣고 본인의 PK를 따로 만듦 N:M)

-- 식별 관계는 자제하도록 비식별 관계가 좋음
-- 복합키도 쓸 수는 있는데 그렇게 자주 나오진 않을듯?
-- 그러면 1:1에서는 식별관계일 때 단일키이고 1:N이나 N:M에서는 식별관계면 복합키가 되겠네

-- 반드시 가져야하고 부모테이블에서 존재하지 않으면 자식 테이블에서 만들 수 없음
-- 부모 PK를 외래키로 사용하고 이를 본인의 PK로 사용함
-- 이거시 식별관계 끈끈하다잉



CREATE TABLE GALLERY(
  GALLERY_NO NUMBER PRIMARY KEY,
  GALLERY_TITLE VARCHAR2(100) NOT NULL,
  GALLERY_WRITER VARCHAR2(30) NOT NULL,
  GALLERY_CONTENT VARCHAR2(4000) NOT NULL,
  COUNT NUMBER DEFAULT 0,
  CREATE_DATE DATE DEFAULT SYSDATE,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  FOREIGN KEY (GALLERY_WRITER) REFERENCES MEMBER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE GAL_FILE(
  FILE_NO NUMBER PRIMARY KEY,
  GALLERY_NO NUMBER NOT NULL,
  ORIGIN_NAME VARCHAR2(100) NOT NULL,
  CHANGE_NAME VARCHAR2(100) NOT NULL,
  FOREIGN KEY (GALLERY_NO) REFERENCES GALLERY(GALLERY_NO) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_GNO NOCACHE;
CREATE SEQUENCE SEQ_FNO NOCACHE;

SELECT * FROM GALLERY;
SELECT * FROM GAL_FILE;

		SELECT
 		       GALLERY_NO
 		     , GALLERY_TITLE
 		     , GALLERY_WRITER
 		     , COUNT
 		     , TO_CHAR(CREATE_DATE, 'YYYY-MM-DD') as createDate
 		     , CHANGE_NAME     
   		  FROM
 		       GALLERY
		  LEFT
 		  JOIN
 		       GAL_FILE USING (GALLERY_NO)
 		 WHERE
 		       STATUS='Y'
 		 ORDER
 		    BY
 		       GALLERY_NO DESC;


SELECT * FROM REPLY;
SELECT * FROM MEMBER;
SELECT * FROM NOTICE;















-- 식당 후기 테이블(작성, 조회 기능 구현할 용도)

--어떤 식당의 후기인지
--후기 내용
--작성 날짜
--별점

CREATE TABLE REVIEW(
	UC_SEQ NUMBER NOT NULL,
	CONTENT NVARCHAR2(1000) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	RATING NUMBER CHECK (RATING BETWEEN 1 AND 5)
);

SELECT * FROM REVIEW;

DROP TABLE REVIEW;


-- 오라클에서는 USER가 키워드이기 때문에 MEMBER라는 식별자로 회원 테이블을 생성하지만
--테이블에 접두사를 붙일 시 USER를 사용할 수 있으
-- 일반적으로 PK의 경우는 숫자 또는 랜덤한 난수값을 사용하는 경우가 많음
CREATE TABLE SEMI_MEMBER(
	MEMBER_ID VARCHAR2(20) PRIMARY KEY,
	MEMBER_PWD VARCHAR2(70) NOT NULL,
	MEMBER_NAME NVARCHAR2(30) NOT NULL,
	ROLE VARCHAR2(20) NOT NULL ,
	STATUS CHAR(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))
);

SELECT * FROM SEMI_MEMBER;

CREATE TABLE KOR_USER(
	USER_NO NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(20) NOT NULL UNIQUE, 
	USER_PWD VARCHAR2(70) NOT NULL,
	USER_NAME NVARCHAR2(20) NOT NULL,
	ENROLL_DATE DATE DEFAULT SYSDATE,
	ROLE VARCHAR2(20) NOT NULL ,
	STATUS CHAR(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))
);

DROP TABLE KOR_USER;

SELECT * FROM KOR_USER;

CREATE SEQUENCE SEQ_KOR NOCACHE;

CREATE TABLE SEMI_TOKEN(
	MEMBER_ID VARCHAR2(20) NOT NULL REFERENCES SEMI_MEMBER ON DELETE CASCADE,
	TOKEN VARCHAR2(300) NOT NULL,
	EXPIRATION NUMBER NOT NULL	
);

SELECT * FROM SEMI_TOKEN;

------------------------------------------------------

	CREATE TABLE SEMI_BOARD(
		BOARD_NO NUMBER PRIMARY KEY,
		BOARD_TITLE NVARCHAR2(200) NOT NULL,
		BOARD_CONTENT NVARCHAR2(2000) NOT NULL,
		BOARD_WRITER VARCHAR2(20) NOT NULL REFERENCES SEMI_MEMBER,
		FILE_URL NVARCHAR2(200),
		CREATE_DATE DATE DEFAULT SYSDATE,
		STATUS CHAR(1) DEFAULT 'Y' CHECK(STATUS IN ('Y', 'N'))
	);
	
	CREATE SEQUENCE SEQ_SBN NOCACHE;
	
	SELECT * FROM SEMI_BOARD;















